<#
.SYNOPSIS
    Reports module for ASA
#>

function Show-ReportsMenu {
    Clear-Host
    Write-Host "`n  📊 Generate Reports" -ForegroundColor Cyan
    Write-Host "  ───────────────────" -ForegroundColor Gray

    # Ensure Reports directory exists
    $ReportPath = Join-Path $global:ScriptPath 'Reports'
    if (-not (Test-Path $ReportPath)) {
        New-Item -Path $ReportPath -ItemType Directory -Force | Out-Null
    }

    # Generate timestamped filename
    $timestamp = Get-Date -Format 'yyyyMMdd_HHmmss'
    $ReportFile = Join-Path $ReportPath "ASA_Report_$timestamp.html"

    # Gather system info
    $os   = Get-CimInstance Win32_OperatingSystem -ErrorAction SilentlyContinue
    $cs   = Get-CimInstance Win32_ComputerSystem -ErrorAction SilentlyContinue
    $cpu  = Get-CimInstance Win32_Processor -ErrorAction SilentlyContinue | Select-Object -First 1
    $bios = Get-CimInstance Win32_BIOS -ErrorAction SilentlyContinue

    if (-not $os -or -not $cs) {
        Write-Host "  ❌ Failed to retrieve system information." -ForegroundColor Red
        Pause
        return
    }

    # ---[ Build HTML Report ]---
    $html = @"
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>ASA System Report</title>
  <style>
    body { font-family: 'Segoe UI', Arial, sans-serif; margin: 2rem; background: #f8f9fa; color: #212529; }
    h1 { color: #0d6efd; }
    h2 { border-bottom: 2px solid #0d6efd; padding-bottom: 0.3rem; margin-top: 2rem; }
    table { border-collapse: collapse; width: 100%; max-width: 800px; }
    th, td { text-align: left; padding: 8px 12px; border-bottom: 1px solid #dee2e6; }
    th { width: 220px; background: #e9ecef; font-weight: 600; }
    .footer { margin-top: 2rem; font-size: 0.9rem; color: #6c757d; }
  </style>
</head>
<body>
  <h1>🤖 Aaron System Assistant — System Report</h1>
  <p><strong>Generated:</strong> $(Get-Date -Format 'yyyy-MM-dd HH:mm:ss')</p>
  <p><strong>User:</strong> $env:USERNAME</p>
  <p><strong>Computer:</strong> $env:COMPUTERNAME</p>

  <h2>🖥️ System</h2>
  <table>
    <tr><th>Computer Name</th><td>$($cs.Name)</td></tr>
    <tr><th>Manufacturer</th><td>$($cs.Manufacturer)</td></tr>
    <tr><th>Model</th><td>$($cs.Model)</td></tr>
    <tr><th>OS</th><td>$($os.Caption) (Build $($os.BuildNumber))</td></tr>
    <tr><th>Install Date</th><td>$($os.InstallDate)</td></tr>
    <tr><th>Last Boot</th><td>$($os.LastBootUpTime)</td></tr>
  </table>

  <h2>⚙️ Hardware</h2>
  <table>
    <tr><th>CPU</th><td>$($cpu.Name)</td></tr>
    <tr><th>Cores / Logical</th><td>$($cpu.NumberOfCores) / $($cpu.NumberOfLogicalProcessors)</td></tr>
    <tr><th>Total RAM</th><td>$([math]::Round($cs.TotalPhysicalMemory/1GB,2)) GB</td></tr>
    <tr><th>BIOS Version</th><td>$($bios.SMBIOSBIOSVersion)</td></tr>
    <tr><th>BIOS Date</th><td>$($bios.ReleaseDate)</td></tr>
  </table>

  <h2>🧠 Memory Snapshot</h2>
  <table>
    <tr><th>Free Physical Memory</th><td>$([math]::Round($os.FreePhysicalMemory/1MB,2)) GB</td></tr>
    <tr><th>Total Visible Memory</th><td>$([math]::Round($os.TotalVisibleMemorySize/1MB,2)) GB</td></tr>
    <tr><th>Memory Usage</th><td>$([math]::Round((($os.TotalVisibleMemorySize - $os.FreePhysicalMemory) / $os.TotalVisibleMemorySize) * 100))%</td></tr>
  </table>

  <div class="footer">
    Report generated by <strong>ASA v$(Get-Content VERSION)</strong> — Aaron System Assistant
  </div>
</body>
</html>
"@

    # Save the report
    $html | Out-File -FilePath $ReportFile -Encoding UTF8
    Write-Host "`n  ✅ Report saved:" -ForegroundColor Green
    Write-Host "     $ReportFile" -ForegroundColor Gray
    Write-ASALog "Report generated: $ReportFile" -Level Info

    # Ask to open
    $open = Read-Host "`n  Open report now? (Y/N)"
    if ($open -match '^[Yy]') {
        Start-Process $ReportFile
        Write-Host "  📂 Report opened in default browser." -ForegroundColor Gray
    }

    Pause
}

Export-ModuleMember -Function Show-ReportsMenu